apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-wasm-yaml
spec:
  template:
    spec:
      containers:
        - image: docker.io/aslom/tinygo-wasm-wagi:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
